#!/usr/bin/expect
spawn telnet localhost 9051
expect "Escape character is '^]'."
send "authenticate \"<Your PAssword Here (Set inside the torrc)>\"\r"
expect "250 OK"
sleep 3
send "signal newnym\r"
expect "250 OK"
sleep 2
send "\x1D\r"
expect "telnet>"
send "q"
